### ISSUE TITLE
docs format?

### ISSUE THREAD

**Issue by nsheff** [pepkit/eido#13]
@stolarczyk is the mkdocs serving working for you like this? Here's what I get;

```
~/code/eido$ mkdocs serve
INFO    -  Building documentation... 
WARNING -  Config value: 'pypi_name'. Warning: Unrecognised configuration name: pypi_name 
Running AutoDocumenter plugin

[Errno 2] No such file or directory: '/home/nsheff/code/eido/docs_jupyter/build/cli.md'
```
is this something local to my setup? I can build other sites without problem...

**Comment by stolarczyk** [comment]
> is this something local to my setup? 

no, now I see that I have the same issue. Interestingly, the pypi link works just fine..

**Comment by nsheff** [comment]
The problem isn't the pypi name warning, that's a red herring -- it's related to the plugin and always shows up.

the problem is the second thing. i think the folder structure may be incorrect

**Comment by stolarczyk** [comment]
It works in my hands. 

what version of our mkdocs plugin are you using? The latest is v0.3.2. I remember working with jupyternb paths for this release.

**Comment by nsheff** [comment]
Ok it works with an update you're right.
