### ISSUE TITLE
Docs questions 

### ISSUE THREAD

**Issue by nsheff** [pepkit/eido#18]
## Features list

I'm trying to add to the docs a list of how eido differs from basic jsonschema. I don't think this is listed anywhere. is this complete?

1. **required input files**. Eido adds `required_input_attrs`, which allows a schema author to specify which attributes must point to files that exist.
2. **optional input files**. `input_attrs` specifies which attributes point to files that may or may not exist.
3. **project and sample validation**. Eido validates project attributes separately from sample attributes.
4. **schema imports**. Eido adds `imports` section that lists schemas that should be validate prior to this schema (more detailed description of importing can be found here: http://eido.databio.org/en/dev/demo/)
5. **automatic multi value support**. Eido validates successfully for singular or plural `Sample` attributes of types: "string", "number", "boolean" (if schema restricts an attribute to type X, an array of Xs is also valid).

## Docs location

Since eido is really only relevant in the context of PEP, do you think I should consolidate the eido docs page into the new pep spec site? I mean, we've already basically started documenting eido at pep.databio.org... so as I'm trying to make this a self-contained docs page, I'm realizing that I'm duplicating a lot of info...

**Comment by nsheff** [comment]
I guess a related follow-up question is: where should we document 'how to write a PEP schema' ? Does it go with eido or with PEP docs? Right now it's here: http://pep.databio.org/en/latest/howto_schema/

It's also incomplete

**Comment by nsheff** [comment]
another one: handling string or array for attributes

**Comment by stolarczyk** [comment]
> is this complete? 

I added two point to your list

> Since eido is really only relevant in the context of PEP, do you think I should consolidate the eido docs page into the new pep spec site?

hmmm do you think we should remove eido docs altogether and just make it a part of PEP spec?

**Comment by nsheff** [comment]
> hmmm do you think we should remove eido docs altogether and just make it a part of PEP spec?

I keep going back and forth... 

option 1: No eido-specific docs, just consolodate these docs into pepspec
option 2: keep docs separate...but then what goes where? I guess I'd put the 'how to write a schema' docs into the eido page.

Now I'm leaning toward option 2

**Comment by stolarczyk** [comment]
The fact that eido docs have grown (especially the jupyter notebooks) also justifies making it separate.

**Comment by nsheff** [comment]
> I added two points to your list

Thanks, got it. What do you think about the 'ngs_inputs' thing we used to have in the pipeline interface? is this worth adding?

**Comment by nsheff** [comment]
> The fact that eido docs have grown (especially the jupyter notebooks) also justifies making it separate.

Alright, I'll do it that way.

**Comment by nsheff** [comment]
Ok I've gone through the docs. I added some details to the intro and added the section on 'writing a schema'. deployed on dev here:

http://eido.databio.org/en/dev/

I'll now remove those docs from pepspec.

let me know what you think

**Comment by stolarczyk** [comment]
> What do you think about the 'ngs_inputs' thing we used to have in the pipeline interface? is this worth adding?

What exactly was the purpose of this? I can't find any docs about it. Currently there's nothing left in looper that would respect this

**Comment by nsheff** [comment]
Ok. let's drop it for now.

what it did was, if you told looper 'this is an NGS input', then it had some functions that could automatically determine some attributes, like "is this paired end or single end?" and "what is the length of reads". it was kind of nice to not have to include those as sample attributes because they could be learned from the input -- but only if we flagged which inputs were sequencing reads.

**Comment by nsheff** [comment]
Ok pepspec docs are live now as well. I think I'm happy with the eido and pepspec docs now. let me know if you have any issues.
