### ISSUE TITLE
`convert_project` exits program

### ISSUE THREAD

**Issue by nleroy917** [pepkit/eido#37]
The function definition for [`convert_project`](https://github.com/pepkit/eido/blob/6d074d8dda8c4b8c05a3aeed956863b5aba217de/eido/conversion.py#L33) will successfully convert a pep given a valid filter, however it runs a `sys.exit(0)` which seems like odd behavior. We are utilizing this for the [pephub server](https://github.com/pepkit/pephub) and it results in server crashes.

Attempts to circumvent this by directly calling `run_filter` only display the conversion result to `stdout`, is it possible to return as `yaml` instead of returning `None`?

**Comment by nsheff** [comment]
yeah this should be fixed.
