### ISSUE TITLE
Processed PEP filter

### ISSUE THREAD

**Issue by nsheff** [pepkit/eido#39]
We need to have a built-in filter that returns a processed PEP.

So, the input is, of course, a PEP. The output is a PEP that has run through sample modifiers and project modifiers -- that is, a *processed PEP*.

So, the user who calls the filter, if he wants to spit the output to files, needs to provide several output file paths; in fact, all the possible files that could go into a PEP: 
- project config
- sample table
- subsample table

See PR #38.

All the filter does is load the PEP with peppy, and then return the objects (as strings), which will have been processed.

@nleroy917 does this make sense to you?

**Comment by nsheff** [comment]
In addition the file path output (the `paths` parameter), this filter should also accept a dict of environment variables, which will be used in the processing step. This way, users can provide environment variables, which will be used to expand paths.

The value there is that we can use this to construct a proper processed PEP, with correct local paths, on whatever computing environment, even remotely.

This will be useful for implementing https://github.com/pepkit/pephub/issues/3

**Comment by nleroy917** [comment]
I think. The input to a conversion filter function then needs to be:

```
{
  "paths": {
    "cfg": "/path/to/config,
    "samples": "/path/to/samples"
  },
  "envs": {
    "env1": ...
  }
}
```

And if `paths` is specified, then the files are written to those paths utilizing those `env` vars?

**Comment by nsheff** [comment]
> I think. The input to a conversion filter function then needs to be:
> 
> ```
> {
>   "paths": {
>     "cfg": "/path/to/config,
>     "samples": "/path/to/samples"
>   },
>   "envs": {
>     "env1": ...
>   }
> }
> ```
> 
> And if `paths` is specified, then the files are written to those paths utilizing those `env` vars?

Yep! you got it.

Specifically, the paths may be something like `"cfg": "${env1}/subpath/to/config"` Hence the need for `expandpath` for the env vars.

**Comment by nsheff** [comment]
> Does a filter need then to set these env variables when it runs? 

Something like this... or else, some other way to just make those available to the `expandpath` functions that get used within Peppy. I'd have to dive into peppy and do some trial and error to say exactly how to do it. your solution may work.

> Does something like this make sense

Well, you'll need to convert these into *files*, ultimately. So they'll have to be string representations. Remember, the output of a filter is one or more files. So you're on the right lines, but it also has to include the subsamples file, I guess (unless you're using the new one-file sample table approach, which may be better).

**Comment by nleroy917** [comment]
Presently, the wrapper around the conversion filters passes a `peppy.Project` instance and a `plugin_kwargs` `dict`. Does it make sense to just utilize that to pass the file paths?

```python
plugin_kwargs = {
  "paths": {
    "cfg": "/path/to/config,
    "samples": "/path/to/samples"
  },
  "envs": {
    "env1": ...
  }
}
```

**Comment by nsheff** [comment]
> I'd be afraid of moving away from the path keyword for fear of breaking anything else inside eido since it feels like that is used heavily

I don't think it is... I wouldn't worry about this... I think this is all new

This is too complicated. Don't use the folder method at all. It should be only `paths`.

**Comment by nsheff** [comment]
> Presently, the wrapper around the conversion filters passes a peppy.Project instance and a plugin_kwargs dict. Does it make sense to just utilize that to pass the file paths?

I'm not sure I really understand the question... For a filter (any filter), to call the filter, you'd give a `paths` parameter, where you'd specify where you want it to spit things out. This is the same for every filter. This is the only way to do it, isn't it?

**Comment by nsheff** [comment]
See comment here, I think this explained it well: https://github.com/pepkit/eido/pull/38/files/2815ecb1b2abac6cbee0cdeea62b939e4c311209#r864395751

**Comment by nleroy917** [comment]
yeah I think that makes sense, and I'm trying to switch over to that implementation
