### ISSUE TITLE
Hitting an `ImportError` through indirect dependency on `eido` on Python 3.10

### ISSUE THREAD

**Issue by vreuter** [pepkit/eido#67]
```shell
...
...
...
../../../.cache/pypoetry/virtualenvs/looptrace-FyWUP9y7-py3.10/lib/python3.10/site-packages/pypiper/__init__.py:6: in <module>
    from .manager import *
../../../.cache/pypoetry/virtualenvs/looptrace-FyWUP9y7-py3.10/lib/python3.10/site-packages/pypiper/manager.py:32: in <module>
    from pipestat import PipestatError, PipestatManager
../../../.cache/pypoetry/virtualenvs/looptrace-FyWUP9y7-py3.10/lib/python3.10/site-packages/pipestat/__init__.py:8: in <module>
    from .pipestat import (
../../../.cache/pypoetry/virtualenvs/looptrace-FyWUP9y7-py3.10/lib/python3.10/site-packages/pipestat/pipestat.py:24: in <module>
    from .reports import HTMLReportBuilder, _create_stats_objs_summaries
../../../.cache/pypoetry/virtualenvs/looptrace-FyWUP9y7-py3.10/lib/python3.10/site-packages/pipestat/reports.py:13: in <module>
    from eido import read_schema
../../../.cache/pypoetry/virtualenvs/looptrace-FyWUP9y7-py3.10/lib/python3.10/site-packages/eido/__init__.py:7: in <module>
    from .conversion import *
../../../.cache/pypoetry/virtualenvs/looptrace-FyWUP9y7-py3.10/lib/python3.10/site-packages/eido/conversion.py:6: in <module>
    from pkg_resources import iter_entry_points
E   ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by vreuter** [comment]
Is this a known issue, perhaps with specific combinations of versions? I have this dependency through `pypiper`, in turn through `pipestat`.

**Comment by nsheff** [comment]
I don't have any insight into this off the top of my head. I don't think I wrote that. It will need to be investigated, I guess.

**Comment by nsheff** [comment]
Ah. `pip install setuptools`

probably should update this.

**Comment by nsheff** [comment]
I think it's because they removed setuptools from built-in python, creating a backwards incompatibility in some version of python.

**Comment by vreuter** [comment]
OK thanks @nsheff !

> Ah. `pip install setuptools`
> 
> probably should update this.

Do you mean add `setuptools` to my environment, or rather update the packaging for `eido`?
Another option would be to try to adopt one of [these alternatives](https://gist.github.com/ssteinbach/42b3fbccff60ad2409c9178272406c9a#alternatives-for-iter_entry_points) for the function in question here from `setuptools`.
